safe: false
port: 4500
base-url: /
url: http://schoewilliam.legtux.org

ftp_host: legtux.org
ftp_dir: /
ftp_username: schoewilliam

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date


blogoliste:
- text: BlogiGor
  url: http://id-libre.org/blogigor
- text: Coreight
  url: http://coreight.com
- text: Dans la tête du Linuxien
  url: http://tetedulinuxien.fr
- text: fabienwang
  url: http://fabienwang.fr
- text: Identitools
  url: http://identitools.fr
- text: Postblue
  url: http://postblue.info

linkoliste:
- text: <strong>Legtux</strong>
  url: http://legtux.org/
- text: mart-e
  url: http://mart-e.be
- text: Le Hollandais Volant
  url: http://lehollandaisvolant.net/
- text: Source, Radio Campus Bruxelles
  url: http://src.radiocampus.be/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
