safe: false
port: 4000
base-url: /
url: http://schoewilliam.legtux.org

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date

nodes:
- text: diaspora*
  url: https://diaspora-fr.org/u/schoewilliam
- text: Github
  url: https://github.com/Schoewilliam
- text: Mozillians
  url: https://mozillians.org/en-US/u/schoewilliam/
- text: GNU Social
  url: https://status.vinilox.eu/schoewilliam

blogoliste:
- text: BlogiGor
  url: http://id-libre.org/blogigor
- text: Dans la tête du Linuxien
  url: http://tetedulinuxien.fr
- text: fabienwang
  url: http://fabienwang.eliteheberg.fr
- text: Identitools
  url: http://identitools.fr
- text: mart-e
  url: http://mart-e.be
- text: Olivier Dossmann
  url: https://olivier.dossmann.net/blog/
- text: Postblue
  url: http://postblue.info
- text: Vinilox
  url: http://vinilox.eu
- text: younishd
  url: http://younishd.fr/

linkoliste:
- text: Jean Baptiste Favre
  url: http://www.jbfavre.org/
- text: Legtux
  url: http://legtux.org/
- text: Le Hollandais Volant
  url: http://lehollandaisvolant.net/
- text: Ploum
  url: http://ploum.net/
- text: Sebsauvage, les trucs qui l'énervent.
  url: http://www.sebsauvage.net/rhaa/
- text: Source, Radio Campus Bruxelles
  url: http://src.radiocampus.be/

series:
- text: Au Fil du retour
  url: /carnet/aufilduretour.html
- text: Petites de mes nouvelles
  url: /carnet/petitesdemesnouvelles.html

  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
