# Site settings
title_left    : "Niléane"
title_right   : "" # default: ""
description   : "Geography, Design & Tech"
keywords      : "geography, lgbt, design, tech"
url           : https://nileane.fr # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

twitter_username  : "nildeala"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:month/:day/:title.html
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Author settings
author:
  name     : "Niléane"

plugins:
  - jekyll-feed

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
