safe: false
auto: false
server: false
server_port: 4000
base-url: /
url: http://schoewilliam.legtux.org

ftp_host: legtux.org
ftp_dir: /
ftp_username: schoewilliam

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

# Blog Menu
navigation:
- text: archives
  url: /archives
- text: à propos
  url: /apropos
- text: rss
  url: /flux.xml 

ailleurs:
- text: Arch Linux Forums
  url: https://bbs.archlinux.org/profile.php?id=55538
- text: DeviantArt
  url: http://schoewilliam.deviantart.com/
  desc: "Captures d'écran commentées."
- text: Diaspora*
  url: https://joindiaspora.com/u/schoewilliam
- text: Github
  url: https://github.com/Schoewilliam
  desc: "Sources du carnet, fichiers de configurations, dotfiles, …"
- text: reddit
  url: http://www.reddit.com/user/schoelcher/
  desc: "Partage et recommandations de liens."
- text: StatusNet
  url: http://identi.ca/schoewilliam
  desc: "Discussions et réactions (bientôt sur le réseau pumpio)."
- text: Twitter
  url: http://twitter.com/schoewilliam

realisations:
- text: Minisch
  url: http://schoewilliam.legtux.org/minisch
  desc: "Un thème élégant et fonctionnel pour Wordpress"
- text: Expérimentations
  url: /experiments

blogoliste:
- text: BlogiGor
  url: http://id-libre.org/blogigor
- text: Coreight
  url: http://coreight.com
- text: Dans la tête du Linuxien
  url: http://tetedulinuxien.fr
- text: Epinaline
  text: http://www.epinaline.kegtux.org/
- text: Identitools
  url: http://identitools.fr
- text: Postblue
  url: http://postblue.info
- text: Septimo Chimæra
  url: http://septimochimaera.kegtux.org

linkoliste:
- text: Legtux
  url: http://legtux.org/
- text: mart-e
  url: http://mart-e.be
- text: Source, Radio Campus Bruxelles
  url: http://src.radiocampus.be/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style
