## Configuration file

name: Nildëala
url: http://nildëala.fr

author: William Dorffer aka. Nildëala
description: Open web enthusiast. Geography Student. Occasional web designer. I like trains.
title: Nildëala

permalink: /:year/:month/:day/:title.html
markdown: kramdown

gems:

defaults:
  -
    scope:
      path: ""
    values:
      lang: fr
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
