safe: false
port: 4000
base-url: /
url: http://schoewilliam.fr

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
highlighter: pygments
markdown:    kramdown
permalink:   date

# Enter below the title of your weblog/website (use <span></span> to nicely fade out some part of it)
maintitle: Schoewilliam<span>.fr</span>
# Enter below a short description that will sit next to your title.
maindesc: Open web enthusiast, non-writer writer, Iceland dreamer. <a href=/about><span class=oi data-glyph=info></span> About me</a>

# Enter below the items of your main menu
menus:
- text: Carnet
  url: /carnet
- text: Au Fil du retour
  url: /carnet/aufilduretour.html
- text: Apps
  url: /apps

nodes:
- text: diaspora*
  url: https://diaspora-fr.org/u/schoewilliam
- text: Github
  url: https://github.com/Schoewilliam
- text: Mozillians
  url: https://mozillians.org/en-US/u/schoewilliam/
- text: GNU Social
  url: https://status.vinilox.eu/schoewilliam

blogoliste:
- text: BlogiGor
  url: http://id-libre.org/blogigor
- text: Ypnose
  url: http://ywstd.fr/
- text: fabienwang
  url: http://fabienwang.eliteheberg.fr
- text: Identitools
  url: http://identitools.fr
- text: Olivier Dossmann
  url: https://olivier.dossmann.net/blog/
- text: Postblue
  url: http://postblue.info
- text: Vinilox
  url: http://vinilox.eu
- text: younishd
  url: http://younishd.fr/

linkoliste:
- text: Blog de dada
  url: http://www.dadall.info/blog/
- text: Jean Baptiste Favre
  url: http://www.jbfavre.org/
- text: Legtux
  url: http://legtux.org/
- text: Le Hollandais Volant
  url: http://lehollandaisvolant.net/
- text: Ploum
  url: http://ploum.net/
- text: Sebsauvage, les trucs qui l'énervent.
  url: http://www.sebsauvage.net/rhaa/
- text: 22decembre
  url: http://www.22decembre.eu/

series:
- text: Au Fil du retour
  url: /carnet/aufilduretour.html
- text: Petites de mes nouvelles
  url: /carnet/petitesdemesnouvelles.html

  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
