## Configuration file

name: Niléane
url: http://nileane.fr

author: Niléane Dorffer
description: Open web enthusiast. Geography Student. I'm a trans girl who likes trains and Human beings. But mostly trains.
title: Niléane

permalink: /:year/:month/:day/:title.html
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      lang: fr
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
